/**
 * Emits lightweight index modules from the heavy content files.
 *
 * Shared UI (footer link mesh, city chips, hub cards) only needs slugs, names
 * and a couple of preview fields. Importing the full content modules for that
 * dragged every city's prose and every service's copy into the client bundle
 * on EVERY route. These generated indexes are the small surface that shared UI
 * imports instead; the heavy modules are now only reached through route
 * loaders via dynamic import.
 *
 * Generated — do not edit by hand. Run `npm run seo:generate`.
 */
import { statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { cities } = await import(resolve(root, "src/data/cities.ts"));
const { seoServices } = await import(resolve(root, "src/data/services-seo.ts"));
const { breeds } = await import(resolve(root, "src/data/breeds.ts"));
const { cityServices } = await import(resolve(root, "src/data/city-services.ts"));
const { guides } = await import(resolve(root, "src/data/guides.ts"));
// Real modification date of the guide content, so dateModified reflects when
// the articles actually changed rather than when the build ran.
const guidesModified = statSync(resolve(root, "src/data/guides.ts"))
  .mtime.toISOString()
  .slice(0, 10);

const banner = `// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.
`;

const cityIndex = `${banner}
export type CityIndexEntry = {
  slug: string;
  name: string;
  state: string;
  region: string;
  /** First three localities, for hub card previews. */
  areasPreview: string[];
  nearby: string[];
};

export const cityIndex: CityIndexEntry[] = ${JSON.stringify(
  cities.map((c) => ({
    slug: c.slug,
    name: c.name,
    state: c.state,
    region: c.region,
    areasPreview: c.areas.slice(0, 3),
    nearby: c.nearby,
  })),
  null,
  2,
)};

export const cityCount = cityIndex.length;

export const cityIndexBySlug: Record<string, CityIndexEntry> = Object.fromEntries(
  cityIndex.map((c) => [c.slug, c]),
);
`;

const serviceIndex = `${banner}
export type ServiceIndexEntry = {
  slug: string;
  name: string;
  icon: string;
  price: string | null;
  /** Meta description, reused as the hub card blurb. */
  blurb: string;
};

export const serviceIndex: ServiceIndexEntry[] = ${JSON.stringify(
  seoServices.map((s) => ({
    slug: s.slug,
    name: s.name,
    icon: s.icon,
    price: s.price,
    blurb: s.description,
  })),
  null,
  2,
)};

export const serviceIndexBySlug: Record<string, ServiceIndexEntry> = Object.fromEntries(
  serviceIndex.map((s) => [s.slug, s]),
);
`;

const breedIndexSrc = `${banner}
export type BreedIndexEntry = {
  slug: string;
  name: string;
  species: "dog" | "cat";
  coatType: string;
  groomingFrequency: string;
  price: string;
};

export const breedIndex: BreedIndexEntry[] = ${JSON.stringify(
  breeds.map((b) => ({
    slug: b.slug,
    name: b.name,
    species: b.species,
    coatType: b.coatType,
    groomingFrequency: b.groomingFrequency,
    price: b.price,
  })),
  null,
  2,
)};

export const breedCount = breedIndex.length;
`;

// Which city+service combination pages exist. Used to render links on the
// city and service pages so no combination page is an orphan.
const comboIndexSrc = `${banner}
export const cityServicePairs: { citySlug: string; serviceSlug: string }[] = ${JSON.stringify(
  cityServices.map((cs) => ({ citySlug: cs.citySlug, serviceSlug: cs.serviceSlug })),
  null,
  2,
)};

export function servicesForCity(citySlug: string): string[] {
  return cityServicePairs.filter((p) => p.citySlug === citySlug).map((p) => p.serviceSlug);
}

export function citiesForService(serviceSlug: string): string[] {
  return cityServicePairs.filter((p) => p.serviceSlug === serviceSlug).map((p) => p.citySlug);
}
`;

const guideIndexSrc = `${banner}
export type GuideIndexEntry = {
  slug: string;
  name: string;
  category: "seasonal" | "problem" | "how-to";
  icon: string;
  /** Short card blurb — the meta description, trimmed. */
  blurb: string;
};

export const guideIndex: GuideIndexEntry[] = ${JSON.stringify(
  guides.map((g) => ({
    slug: g.slug,
    name: g.name,
    category: g.category,
    icon: g.icon,
    blurb: g.description,
  })),
  null,
  2,
)};

export const guideCount = guideIndex.length;

/** Date the guide content was last edited (file mtime at generation time). */
export const guidesModified = "${guidesModified}";
`;

writeFileSync(resolve(root, "src/data/guide-index.ts"), guideIndexSrc);
writeFileSync(resolve(root, "src/data/city-service-index.ts"), comboIndexSrc);
writeFileSync(resolve(root, "src/data/breed-index.ts"), breedIndexSrc);
writeFileSync(resolve(root, "src/data/city-index.ts"), cityIndex);
writeFileSync(resolve(root, "src/data/service-index.ts"), serviceIndex);

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)}KB`;
console.log(`city-index.ts     ${cities.length} cities  ${kb(cityIndex)}`);
console.log(`service-index.ts  ${seoServices.length} services  ${kb(serviceIndex)}`);
console.log(`breed-index.ts    ${breeds.length} breeds  ${kb(breedIndexSrc)}`);
console.log(`city-service-index.ts  ${cityServices.length} pairs  ${kb(comboIndexSrc)}`);
console.log(`guide-index.ts    ${guides.length} guides  ${kb(guideIndexSrc)}`);
