// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.

export type BreedIndexEntry = {
  slug: string;
  name: string;
  species: "dog" | "cat";
  coatType: string;
  groomingFrequency: string;
  price: string;
};

export const breedIndex: BreedIndexEntry[] = [
  {
    "slug": "golden-retriever",
    "name": "Golden Retriever",
    "species": "dog",
    "coatType": "Double coat, dense water-resistant outer coat with heavy feathering",
    "groomingFrequency": "Every 4-6 weeks, with de-shedding every 3-4 weeks in summer",
    "price": "Rs. 2,500"
  },
  {
    "slug": "labrador-retriever",
    "name": "Labrador Retriever",
    "species": "dog",
    "coatType": "Short, dense double coat with a slightly oily water-repellent top layer",
    "groomingFrequency": "Every 4-6 weeks",
    "price": "Rs. 2,000"
  },
  {
    "slug": "german-shepherd",
    "name": "German Shepherd",
    "species": "dog",
    "coatType": "Double coat, harsh weather-resistant guard hair over a thick woolly undercoat",
    "groomingFrequency": "Every 4-6 weeks, more often during coat blow",
    "price": "Rs. 2,500"
  },
  {
    "slug": "shih-tzu",
    "name": "Shih Tzu",
    "species": "dog",
    "coatType": "Long, fine, continuously growing double coat with a hair-like texture",
    "groomingFrequency": "Every 4 weeks, with daily combing at home",
    "price": "Rs. 2,500"
  },
  {
    "slug": "pug",
    "name": "Pug",
    "species": "dog",
    "coatType": "Short, smooth, dense single coat — fine hair that sheds constantly",
    "groomingFrequency": "Every 4-5 weeks",
    "price": "Rs. 2,000"
  },
  {
    "slug": "beagle",
    "name": "Beagle",
    "species": "dog",
    "coatType": "Short, dense, weather-resistant double coat",
    "groomingFrequency": "Every 5-6 weeks",
    "price": "Rs. 1,500"
  },
  {
    "slug": "siberian-husky",
    "name": "Siberian Husky",
    "species": "dog",
    "coatType": "Very dense double coat — straight guard hair over a thick woolly undercoat",
    "groomingFrequency": "Every 4 weeks, and weekly raking during coat blow",
    "price": "Rs. 2,500"
  },
  {
    "slug": "pomeranian",
    "name": "Pomeranian",
    "species": "dog",
    "coatType": "Double coat — long stand-off guard hair over a short, dense, cottony undercoat",
    "groomingFrequency": "Every 4-5 weeks",
    "price": "Rs. 2,000"
  },
  {
    "slug": "rottweiler",
    "name": "Rottweiler",
    "species": "dog",
    "coatType": "Short, coarse, flat outer coat with a light undercoat on the neck and thighs",
    "groomingFrequency": "Every 5-6 weeks",
    "price": "Rs. 2,000"
  },
  {
    "slug": "indian-pariah-dog",
    "name": "Indian Pariah Dog",
    "species": "dog",
    "coatType": "Short, coarse single coat, close-lying and naturally weather-adapted",
    "groomingFrequency": "Every 8-10 weeks",
    "price": "Rs. 1,500"
  },
  {
    "slug": "cocker-spaniel",
    "name": "Cocker Spaniel",
    "species": "dog",
    "coatType": "Silky medium-length coat with heavy feathering on ears, chest, belly and legs",
    "groomingFrequency": "Every 4-6 weeks",
    "price": "Rs. 2,000"
  },
  {
    "slug": "poodle",
    "name": "Poodle",
    "species": "dog",
    "coatType": "Dense, curly, continuously growing single coat that sheds very little",
    "groomingFrequency": "Every 4-6 weeks, without exception",
    "price": "Rs. 1,500"
  },
  {
    "slug": "dachshund",
    "name": "Dachshund",
    "species": "dog",
    "coatType": "Three varieties — smooth, long-haired and wire-haired, each groomed differently",
    "groomingFrequency": "Every 6-8 weeks for smooth coats, 4-6 for long and wire",
    "price": "Rs. 1,500"
  },
  {
    "slug": "persian-cat",
    "name": "Persian Cat",
    "species": "cat",
    "coatType": "Very long, fine double coat with a dense undercoat that mats readily",
    "groomingFrequency": "Every 4-6 weeks, with daily combing at home",
    "price": "Rs. 2,500"
  },
  {
    "slug": "siamese-cat",
    "name": "Siamese Cat",
    "species": "cat",
    "coatType": "Very short, fine, close-lying single coat with almost no undercoat",
    "groomingFrequency": "Every 8-10 weeks",
    "price": "Rs. 1,500"
  },
  {
    "slug": "maine-coon",
    "name": "Maine Coon",
    "species": "cat",
    "coatType": "Long, shaggy, water-resistant coat, uneven in length with a dense ruff and tail plume",
    "groomingFrequency": "Every 4-6 weeks, with combing two or three times a week",
    "price": "Rs. 2,500"
  },
  {
    "slug": "bengal-cat",
    "name": "Bengal Cat",
    "species": "cat",
    "coatType": "Short, dense, unusually soft pelt-like coat with a glossy finish",
    "groomingFrequency": "Every 6-8 weeks",
    "price": "Rs. 1,500"
  },
  {
    "slug": "indian-domestic-shorthair",
    "name": "Indian Domestic Shorthair",
    "species": "cat",
    "coatType": "Short, fine, close-lying coat naturally suited to a hot climate",
    "groomingFrequency": "Every 8-10 weeks",
    "price": "Rs. 1,500"
  }
];

export const breedCount = breedIndex.length;
