// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.

export type CityIndexEntry = {
  slug: string;
  name: string;
  state: string;
  region: string;
  /** First three localities, for hub card previews. */
  areasPreview: string[];
  nearby: string[];
};

export const cityIndex: CityIndexEntry[] = [
  {
    "slug": "delhi",
    "name": "Delhi",
    "state": "Delhi",
    "region": "North",
    "areasPreview": [
      "Vasant Kunj",
      "Saket",
      "Greater Kailash"
    ],
    "nearby": [
      "gurgaon",
      "noida",
      "ghaziabad",
      "faridabad"
    ]
  },
  {
    "slug": "gurgaon",
    "name": "Gurgaon",
    "state": "Haryana",
    "region": "North",
    "areasPreview": [
      "DLF Phase 1",
      "DLF Phase 5",
      "Golf Course Road"
    ],
    "nearby": [
      "delhi",
      "faridabad",
      "noida"
    ]
  },
  {
    "slug": "noida",
    "name": "Noida",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Sector 62",
      "Sector 18",
      "Sector 50"
    ],
    "nearby": [
      "delhi",
      "ghaziabad",
      "gurgaon"
    ]
  },
  {
    "slug": "ghaziabad",
    "name": "Ghaziabad",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Indirapuram",
      "Vaishali",
      "Vasundhara"
    ],
    "nearby": [
      "delhi",
      "noida",
      "faridabad"
    ]
  },
  {
    "slug": "faridabad",
    "name": "Faridabad",
    "state": "Haryana",
    "region": "North",
    "areasPreview": [
      "Sector 15",
      "Sector 21C",
      "Sector 46"
    ],
    "nearby": [
      "delhi",
      "gurgaon",
      "noida"
    ]
  },
  {
    "slug": "mumbai",
    "name": "Mumbai",
    "state": "Maharashtra",
    "region": "West",
    "areasPreview": [
      "Bandra",
      "Andheri",
      "Powai"
    ],
    "nearby": [
      "thane",
      "navi-mumbai",
      "pune",
      "goa"
    ]
  },
  {
    "slug": "thane",
    "name": "Thane",
    "state": "Maharashtra",
    "region": "West",
    "areasPreview": [
      "Ghodbunder Road",
      "Hiranandani Estate",
      "Majiwada"
    ],
    "nearby": [
      "mumbai",
      "navi-mumbai",
      "nashik"
    ]
  },
  {
    "slug": "navi-mumbai",
    "name": "Navi Mumbai",
    "state": "Maharashtra",
    "region": "West",
    "areasPreview": [
      "Vashi",
      "Nerul",
      "Kharghar"
    ],
    "nearby": [
      "mumbai",
      "thane",
      "pune"
    ]
  },
  {
    "slug": "pune",
    "name": "Pune",
    "state": "Maharashtra",
    "region": "West",
    "areasPreview": [
      "Koregaon Park",
      "Baner",
      "Kothrud"
    ],
    "nearby": [
      "mumbai",
      "navi-mumbai",
      "nashik"
    ]
  },
  {
    "slug": "nashik",
    "name": "Nashik",
    "state": "Maharashtra",
    "region": "West",
    "areasPreview": [
      "Gangapur Road",
      "College Road",
      "Indira Nagar"
    ],
    "nearby": [
      "mumbai",
      "thane",
      "pune"
    ]
  },
  {
    "slug": "nagpur",
    "name": "Nagpur",
    "state": "Maharashtra",
    "region": "Central",
    "areasPreview": [
      "Dharampeth",
      "Civil Lines",
      "Ramdaspeth"
    ],
    "nearby": [
      "raipur",
      "bhopal",
      "indore",
      "pune"
    ]
  },
  {
    "slug": "bengaluru",
    "name": "Bengaluru",
    "state": "Karnataka",
    "region": "South",
    "areasPreview": [
      "Indiranagar",
      "Koramangala",
      "Whitefield"
    ],
    "nearby": [
      "mysuru",
      "chennai",
      "hyderabad"
    ]
  },
  {
    "slug": "mysuru",
    "name": "Mysuru",
    "state": "Karnataka",
    "region": "South",
    "areasPreview": [
      "Vijayanagar",
      "Kuvempunagar",
      "Jayalakshmipuram"
    ],
    "nearby": [
      "bengaluru",
      "coimbatore",
      "kochi"
    ]
  },
  {
    "slug": "hyderabad",
    "name": "Hyderabad",
    "state": "Telangana",
    "region": "South",
    "areasPreview": [
      "Gachibowli",
      "Banjara Hills",
      "Jubilee Hills"
    ],
    "nearby": [
      "bengaluru",
      "vijayawada",
      "visakhapatnam",
      "nagpur"
    ]
  },
  {
    "slug": "chennai",
    "name": "Chennai",
    "state": "Tamil Nadu",
    "region": "South",
    "areasPreview": [
      "Adyar",
      "Anna Nagar",
      "T Nagar"
    ],
    "nearby": [
      "bengaluru",
      "coimbatore",
      "vijayawada"
    ]
  },
  {
    "slug": "coimbatore",
    "name": "Coimbatore",
    "state": "Tamil Nadu",
    "region": "South",
    "areasPreview": [
      "R S Puram",
      "Saibaba Colony",
      "Peelamedu"
    ],
    "nearby": [
      "chennai",
      "kochi",
      "mysuru",
      "bengaluru"
    ]
  },
  {
    "slug": "kochi",
    "name": "Kochi",
    "state": "Kerala",
    "region": "South",
    "areasPreview": [
      "Kakkanad",
      "Panampilly Nagar",
      "Edappally"
    ],
    "nearby": [
      "thiruvananthapuram",
      "coimbatore",
      "mysuru"
    ]
  },
  {
    "slug": "thiruvananthapuram",
    "name": "Thiruvananthapuram",
    "state": "Kerala",
    "region": "South",
    "areasPreview": [
      "Kowdiar",
      "Pattom",
      "Vellayambalam"
    ],
    "nearby": [
      "kochi",
      "coimbatore",
      "mysuru"
    ]
  },
  {
    "slug": "kolkata",
    "name": "Kolkata",
    "state": "West Bengal",
    "region": "East",
    "areasPreview": [
      "Salt Lake",
      "New Town",
      "Ballygunge"
    ],
    "nearby": [
      "bhubaneswar",
      "patna",
      "ranchi",
      "guwahati"
    ]
  },
  {
    "slug": "bhubaneswar",
    "name": "Bhubaneswar",
    "state": "Odisha",
    "region": "East",
    "areasPreview": [
      "Patia",
      "Chandrasekharpur",
      "Saheed Nagar"
    ],
    "nearby": [
      "kolkata",
      "visakhapatnam",
      "ranchi"
    ]
  },
  {
    "slug": "guwahati",
    "name": "Guwahati",
    "state": "Assam",
    "region": "Northeast",
    "areasPreview": [
      "Zoo Road",
      "Beltola",
      "Six Mile"
    ],
    "nearby": [
      "kolkata",
      "bhubaneswar",
      "ranchi"
    ]
  },
  {
    "slug": "patna",
    "name": "Patna",
    "state": "Bihar",
    "region": "East",
    "areasPreview": [
      "Boring Road",
      "Kankarbagh",
      "Rajendra Nagar"
    ],
    "nearby": [
      "ranchi",
      "varanasi",
      "kolkata",
      "lucknow"
    ]
  },
  {
    "slug": "ranchi",
    "name": "Ranchi",
    "state": "Jharkhand",
    "region": "East",
    "areasPreview": [
      "Lalpur",
      "Harmu",
      "Kanke Road"
    ],
    "nearby": [
      "patna",
      "kolkata",
      "bhubaneswar",
      "varanasi"
    ]
  },
  {
    "slug": "lucknow",
    "name": "Lucknow",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Gomti Nagar",
      "Hazratganj",
      "Indira Nagar"
    ],
    "nearby": [
      "kanpur",
      "varanasi",
      "agra",
      "delhi"
    ]
  },
  {
    "slug": "kanpur",
    "name": "Kanpur",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Swaroop Nagar",
      "Civil Lines",
      "Kakadeo"
    ],
    "nearby": [
      "lucknow",
      "agra",
      "varanasi"
    ]
  },
  {
    "slug": "varanasi",
    "name": "Varanasi",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Sigra",
      "Lanka",
      "Bhelupur"
    ],
    "nearby": [
      "lucknow",
      "patna",
      "kanpur",
      "ranchi"
    ]
  },
  {
    "slug": "agra",
    "name": "Agra",
    "state": "Uttar Pradesh",
    "region": "North",
    "areasPreview": [
      "Taj Ganj",
      "Dayal Bagh",
      "Sikandra"
    ],
    "nearby": [
      "delhi",
      "faridabad",
      "jaipur",
      "kanpur"
    ]
  },
  {
    "slug": "jaipur",
    "name": "Jaipur",
    "state": "Rajasthan",
    "region": "North",
    "areasPreview": [
      "Malviya Nagar",
      "Vaishali Nagar",
      "Mansarovar"
    ],
    "nearby": [
      "jodhpur",
      "udaipur",
      "agra",
      "delhi"
    ]
  },
  {
    "slug": "jodhpur",
    "name": "Jodhpur",
    "state": "Rajasthan",
    "region": "North",
    "areasPreview": [
      "Ratanada",
      "Sardarpura",
      "Shastri Nagar"
    ],
    "nearby": [
      "jaipur",
      "udaipur",
      "ahmedabad"
    ]
  },
  {
    "slug": "udaipur",
    "name": "Udaipur",
    "state": "Rajasthan",
    "region": "North",
    "areasPreview": [
      "Hiran Magri",
      "Sector 14",
      "Fatehpura"
    ],
    "nearby": [
      "jaipur",
      "jodhpur",
      "ahmedabad",
      "vadodara"
    ]
  },
  {
    "slug": "ahmedabad",
    "name": "Ahmedabad",
    "state": "Gujarat",
    "region": "West",
    "areasPreview": [
      "Satellite",
      "Bodakdev",
      "Vastrapur"
    ],
    "nearby": [
      "vadodara",
      "surat",
      "rajkot",
      "udaipur"
    ]
  },
  {
    "slug": "surat",
    "name": "Surat",
    "state": "Gujarat",
    "region": "West",
    "areasPreview": [
      "Vesu",
      "Adajan",
      "Piplod"
    ],
    "nearby": [
      "vadodara",
      "ahmedabad",
      "mumbai",
      "rajkot"
    ]
  },
  {
    "slug": "vadodara",
    "name": "Vadodara",
    "state": "Gujarat",
    "region": "West",
    "areasPreview": [
      "Alkapuri",
      "Gotri",
      "Akota"
    ],
    "nearby": [
      "ahmedabad",
      "surat",
      "rajkot",
      "udaipur"
    ]
  },
  {
    "slug": "rajkot",
    "name": "Rajkot",
    "state": "Gujarat",
    "region": "West",
    "areasPreview": [
      "Kalawad Road",
      "University Road",
      "Mavdi"
    ],
    "nearby": [
      "ahmedabad",
      "vadodara",
      "surat"
    ]
  },
  {
    "slug": "indore",
    "name": "Indore",
    "state": "Madhya Pradesh",
    "region": "Central",
    "areasPreview": [
      "Vijay Nagar",
      "Palasia",
      "Nipania"
    ],
    "nearby": [
      "bhopal",
      "nagpur",
      "vadodara",
      "ahmedabad"
    ]
  },
  {
    "slug": "bhopal",
    "name": "Bhopal",
    "state": "Madhya Pradesh",
    "region": "Central",
    "areasPreview": [
      "Arera Colony",
      "Shahpura",
      "Kolar Road"
    ],
    "nearby": [
      "indore",
      "nagpur",
      "raipur"
    ]
  },
  {
    "slug": "raipur",
    "name": "Raipur",
    "state": "Chhattisgarh",
    "region": "Central",
    "areasPreview": [
      "Shankar Nagar",
      "Devendra Nagar",
      "Telibandha"
    ],
    "nearby": [
      "nagpur",
      "bhopal",
      "bhubaneswar",
      "ranchi"
    ]
  },
  {
    "slug": "chandigarh",
    "name": "Chandigarh",
    "state": "Chandigarh",
    "region": "North",
    "areasPreview": [
      "Sector 17",
      "Sector 35",
      "Sector 8"
    ],
    "nearby": [
      "ludhiana",
      "amritsar",
      "dehradun",
      "delhi"
    ]
  },
  {
    "slug": "ludhiana",
    "name": "Ludhiana",
    "state": "Punjab",
    "region": "North",
    "areasPreview": [
      "Sarabha Nagar",
      "Model Town",
      "Civil Lines"
    ],
    "nearby": [
      "chandigarh",
      "amritsar",
      "delhi"
    ]
  },
  {
    "slug": "amritsar",
    "name": "Amritsar",
    "state": "Punjab",
    "region": "North",
    "areasPreview": [
      "Ranjit Avenue",
      "Green Avenue",
      "Lawrence Road"
    ],
    "nearby": [
      "ludhiana",
      "chandigarh",
      "delhi"
    ]
  },
  {
    "slug": "dehradun",
    "name": "Dehradun",
    "state": "Uttarakhand",
    "region": "North",
    "areasPreview": [
      "Rajpur Road",
      "Dalanwala",
      "Vasant Vihar"
    ],
    "nearby": [
      "chandigarh",
      "delhi",
      "ghaziabad",
      "noida"
    ]
  },
  {
    "slug": "visakhapatnam",
    "name": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "region": "South",
    "areasPreview": [
      "MVP Colony",
      "Dwaraka Nagar",
      "Madhurawada"
    ],
    "nearby": [
      "vijayawada",
      "bhubaneswar",
      "hyderabad"
    ]
  },
  {
    "slug": "vijayawada",
    "name": "Vijayawada",
    "state": "Andhra Pradesh",
    "region": "South",
    "areasPreview": [
      "Benz Circle",
      "Labbipet",
      "Patamata"
    ],
    "nearby": [
      "visakhapatnam",
      "hyderabad",
      "chennai"
    ]
  },
  {
    "slug": "goa",
    "name": "Goa",
    "state": "Goa",
    "region": "West",
    "areasPreview": [
      "Panaji",
      "Porvorim",
      "Margao"
    ],
    "nearby": [
      "mumbai",
      "pune",
      "navi-mumbai"
    ]
  }
];

export const cityCount = cityIndex.length;

export const cityIndexBySlug: Record<string, CityIndexEntry> = Object.fromEntries(
  cityIndex.map((c) => [c.slug, c]),
);
