// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.

export const cityServicePairs: { citySlug: string; serviceSlug: string }[] = [
  {
    "citySlug": "delhi",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "delhi",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "delhi",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "mumbai",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "mumbai",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "mumbai",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "bengaluru",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "bengaluru",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "bengaluru",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "hyderabad",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "hyderabad",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "hyderabad",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "chennai",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "chennai",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "chennai",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "pune",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "pune",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "pune",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "gurgaon",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "gurgaon",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "gurgaon",
    "serviceSlug": "tick-and-flea-treatment"
  },
  {
    "citySlug": "noida",
    "serviceSlug": "dog-grooming-at-home"
  },
  {
    "citySlug": "noida",
    "serviceSlug": "cat-grooming-at-home"
  },
  {
    "citySlug": "noida",
    "serviceSlug": "tick-and-flea-treatment"
  }
];

export function servicesForCity(citySlug: string): string[] {
  return cityServicePairs.filter((p) => p.citySlug === citySlug).map((p) => p.serviceSlug);
}

export function citiesForService(serviceSlug: string): string[] {
  return cityServicePairs.filter((p) => p.serviceSlug === serviceSlug).map((p) => p.citySlug);
}
