// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.

export type GuideIndexEntry = {
  slug: string;
  name: string;
  category: "seasonal" | "problem" | "how-to";
  icon: string;
  /** Short card blurb — the meta description, trimmed. */
  blurb: string;
};

export const guideIndex: GuideIndexEntry[] = [
  {
    "slug": "is-it-safe-to-shave-your-dog-in-summer",
    "name": "Is It Safe to Shave Your Dog in Summer?",
    "category": "seasonal",
    "icon": "ThermometerSun",
    "blurb": "Shaving a double coat does not cool a dog down and can permanently change how the coat regrows. What to do instead, and which coats can safely be clipped."
  },
  {
    "slug": "how-to-remove-matted-fur",
    "name": "How to Remove Matted Fur Without Hurting Your Dog",
    "category": "problem",
    "icon": "Scissors",
    "blurb": "Mats pull on skin with every step. How to work a knot out from the tip inward, which mats must be clipped rather than brushed, and where they form first."
  },
  {
    "slug": "how-often-should-you-groom-your-dog",
    "name": "How Often Should You Groom Your Dog?",
    "category": "how-to",
    "icon": "CalendarClock",
    "blurb": "Honest grooming intervals by coat type, including the dogs that need very little. What runs on its own schedule, and the signs you have left it too long."
  },
  {
    "slug": "helping-a-dog-scared-of-grooming",
    "name": "Helping a Dog Who Is Scared of Grooming",
    "category": "problem",
    "icon": "HeartHandshake",
    "blurb": "Why grooming frightens some dogs, how to prepare in the week before a session, and what to do in the room. When fear is actually pain and needs a vet."
  },
  {
    "slug": "monsoon-pet-care",
    "name": "Monsoon Pet Care: Keeping a Coat Healthy in the Rains",
    "category": "seasonal",
    "icon": "CloudRain",
    "blurb": "Monsoon coat trouble is about staying damp at the skin, not getting rained on. Drying technique, paws, ears and flat-living problems through the Indian rains."
  },
  {
    "slug": "summer-pet-care",
    "name": "Summer Pet Care for Indian Heat",
    "category": "seasonal",
    "icon": "Sun",
    "blurb": "Airflow beats haircuts. Paw pad safety on hot roads, coat work that genuinely helps, bathing and hard water, and the heat signs that mean stop and call a vet."
  },
  {
    "slug": "winter-pet-care",
    "name": "Winter Pet Care and Coat Maintenance",
    "category": "seasonal",
    "icon": "Snowflake",
    "blurb": "Indian winters range from a Delhi cold snap to a Chennai non-event. Who feels the cold, why grooming should not stop, and how to bathe safely in cold weather."
  },
  {
    "slug": "tick-season-in-india",
    "name": "Tick Season in India: When to Check and Where to Look",
    "category": "seasonal",
    "icon": "Bug",
    "blurb": "The brown dog tick lives indoors in India, so there is no true off-season. Regional timing, the exact spots ticks hide, safe removal, and treating the house."
  },
  {
    "slug": "why-does-my-dog-smell",
    "name": "Why Does My Dog Smell, Even After a Bath?",
    "category": "problem",
    "icon": "Wind",
    "blurb": "Most persistent dog smell comes from a coat that dried on the surface, or from bedding and collars. When it is not grooming, a smell can be a health sign."
  },
  {
    "slug": "brushing-your-dog-at-home",
    "name": "Brushing Your Dog at Home, Properly",
    "category": "how-to",
    "icon": "Brush",
    "blurb": "Line brushing, the metal comb test, and choosing a tool that suits the coat. The at-home habit that prevents more problems than anything you can book."
  },
  {
    "slug": "how-to-bathe-your-dog-at-home",
    "name": "How to Bathe Your Dog at Home",
    "category": "how-to",
    "icon": "Droplets",
    "blurb": "A bucket, a mug and a method: water temperature, the order that keeps shampoo out of the eyes, and why the rinse should take longer than the wash."
  },
  {
    "slug": "how-to-dry-your-dog-properly",
    "name": "How to Dry Your Dog Properly",
    "category": "how-to",
    "icon": "Fan",
    "blurb": "Towels and patience beat a hot hairdryer every time. How to get a coat dry at the skin, and how long that honestly takes in Indian humidity."
  },
  {
    "slug": "double-coat-or-single-coat",
    "name": "Double Coat or Single Coat? How to Tell",
    "category": "how-to",
    "icon": "Layers",
    "blurb": "A finger-part at the shoulder answers it in seconds. How to identify your dog's coat type, and everything that changes once you know the answer."
  },
  {
    "slug": "is-my-dogs-shedding-normal",
    "name": "Is My Dog's Shedding Normal?",
    "category": "problem",
    "icon": "Feather",
    "blurb": "Most Indian dogs shed a little all year and a lot twice a year. What ordinary shedding looks like, and the signs that point to hair loss instead."
  },
  {
    "slug": "cleaning-your-dogs-ears-safely",
    "name": "Cleaning Your Dog's Ears Safely",
    "category": "how-to",
    "icon": "Ear",
    "blurb": "Wipe the flap, never the canal. What a safe home ear clean actually covers, why cotton buds make things worse, and the signs that mean a vet instead."
  },
  {
    "slug": "trimming-your-dogs-nails-at-home",
    "name": "Trimming Your Dog's Nails at Home",
    "category": "how-to",
    "icon": "PawPrint",
    "blurb": "Where the quick sits, how much to take off a black nail, what to do if you nick one, and why plenty of pavement-walked dogs never need a trim at all."
  },
  {
    "slug": "grooming-a-cat-who-hates-being-brushed",
    "name": "Grooming a Cat Who Hates Being Brushed",
    "category": "problem",
    "icon": "Cat",
    "blurb": "Cats stop tolerating handling suddenly rather than gradually. Reading the warning signs, picking tools for thin skin, and working in ninety-second sessions."
  },
  {
    "slug": "when-can-a-puppy-have-its-first-groom",
    "name": "When Can a Puppy Have Its First Groom?",
    "category": "how-to",
    "icon": "Baby",
    "blurb": "Handling starts at home in week one. What a sensible first appointment covers, why it is not a full haircut, and the timing question to put to your vet."
  },
  {
    "slug": "grooming-an-older-dog-safely",
    "name": "Grooming an Older Dog Safely",
    "category": "problem",
    "icon": "HandHeart",
    "blurb": "Standing still is the hard part. How grooming changes for a dog in its later years, what we adapt, and where our job stops and your vet's begins."
  },
  {
    "slug": "questions-to-ask-before-booking-a-groomer",
    "name": "Questions to Ask Before Booking a Groomer",
    "category": "how-to",
    "icon": "ClipboardCheck",
    "blurb": "Six questions that separate a careful groomer from a careless one, including the ones we would want you to ask us before handing over your dog."
  },
  {
    "slug": "preventing-mats-between-grooms",
    "name": "Preventing Mats Between Grooms",
    "category": "how-to",
    "icon": "CalendarCheck",
    "blurb": "Most mats are made by harnesses, damp coats and a comb kept in a cupboard. Choosing a coat length you can maintain and a routine you will actually keep."
  },
  {
    "slug": "hard-water-and-your-pets-coat",
    "name": "Hard Water and Your Pet's Coat",
    "category": "problem",
    "icon": "GlassWater",
    "blurb": "Mineral residue from borewell and tanker water dulls a coat and stops shampoo rinsing out. What helps in Hyderabad, Chennai and Delhi, and what does not."
  }
];

export const guideCount = guideIndex.length;

/** Date the guide content was last edited (file mtime at generation time). */
export const guidesModified = "2026-09-11";
