// GENERATED by scripts/generate-indexes.mjs — do not edit by hand.
// Lightweight lookup data for shared UI. The full content lives in
// ./cities.ts and ./services-seo.ts, which are loaded only by route loaders.

export type ServiceIndexEntry = {
  slug: string;
  name: string;
  icon: string;
  price: string | null;
  /** Meta description, reused as the hub card blurb. */
  blurb: string;
};

export const serviceIndex: ServiceIndexEntry[] = [
  {
    "slug": "dog-grooming-at-home",
    "name": "Dog Grooming at Home",
    "icon": "Dog",
    "price": "Rs. 2,000",
    "blurb": "Book dog grooming at home anywhere in India. Bath, blow dry, trim, nails and ears done at your doorstep from Rs. 2,000. Call +91 99905 99189, open 7 days."
  },
  {
    "slug": "cat-grooming-at-home",
    "name": "Cat Grooming at Home",
    "icon": "Cat",
    "price": "Rs. 2,000",
    "blurb": "Gentle cat grooming at home across India. Quiet, low-restraint handling for Persians, Indies and Ragdolls at Rs. 2,000. Call +91 99905 99189 to book a slot."
  },
  {
    "slug": "pet-spa-bath",
    "name": "Pet Spa Bath",
    "icon": "Bath",
    "price": "Rs. 1,500",
    "blurb": "A full spa bath for dogs and cats at your doorstep for Rs. 1,500. Warm bath, deep conditioning, complete blow dry and nails. Book on WhatsApp, open 7 days."
  },
  {
    "slug": "dog-haircut-and-styling",
    "name": "Dog Haircut & Breed-Specific Styling",
    "icon": "Scissors",
    "price": "Rs. 1,500",
    "blurb": "Dog haircut at home by trained groomers: teddy bear, puppy cut, summer trim or breed standard. Rs. 1,500 for haircut only. Call +91 99905 99189 to book."
  },
  {
    "slug": "tick-and-flea-treatment",
    "name": "Tick & Flea Treatment for Pets",
    "icon": "Bug",
    "price": "Rs. 2,500",
    "blurb": "Anti-tick and flea grooming bath at your doorstep, Rs. 2,500. Medicated wash, manual tick removal and coat check by trained groomers. Book on WhatsApp today."
  },
  {
    "slug": "pet-nail-trimming",
    "name": "Pet Nail Trimming & Paw Care",
    "icon": "PawPrint",
    "price": null,
    "blurb": "Doorstep nail trimming and paw care for dogs and cats across India. Quick, calm, no clinic visit. Included with every grooming package. Open 7 days a week."
  },
  {
    "slug": "de-shedding-treatment",
    "name": "De-Shedding Treatment for Dogs & Cats",
    "icon": "Wind",
    "price": "Rs. 2,500",
    "blurb": "Cut shedding dramatically with a doorstep de-shedding treatment at Rs. 2,500. Undercoat removal for Huskies, Goldens, Spitz, Persians and Indies. Open 7 days."
  },
  {
    "slug": "puppy-first-grooming",
    "name": "Puppy's First Grooming",
    "icon": "Baby",
    "price": "Rs. 1,500",
    "blurb": "A gentle first grooming session for puppies at home, Rs. 1,500. Short, calm and confidence-building with trained groomers. Call +91 99905 99189 to book."
  },
  {
    "slug": "senior-pet-grooming",
    "name": "Senior Pet Grooming",
    "icon": "Heart",
    "price": "Rs. 2,500",
    "blurb": "Patient at-home grooming for senior dogs and cats at Rs. 2,500. Short sessions, non-slip support, arthritis-aware handling. Doorstep service, open 7 days."
  },
  {
    "slug": "mobile-pet-grooming",
    "name": "Mobile Pet Grooming at Your Doorstep",
    "icon": "Truck",
    "price": "Rs. 2,000",
    "blurb": "Mobile pet grooming that comes to you anywhere in India. Groomers bring every tool to your door, 8 AM to 8 PM, 7 days. Full grooming Rs. 2,000. Book now."
  }
];

export const serviceIndexBySlug: Record<string, ServiceIndexEntry> = Object.fromEntries(
  serviceIndex.map((s) => [s.slug, s]),
);
