// GENERATED by scripts/generate-seo-files.mjs — do not edit by hand.
// Resolved at build time from: fallback literal (not yet verified)
export const SITE_ORIGIN = "https://www.petsgroomers.in";
export const SITE_ORIGIN_SOURCE = "fallback literal (not yet verified)";
